version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: deployer_rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        restart: always
        networks:
            - deployer_network

    fontend:
        container_name: deployer_frontend
        build:
            context: ./frontend
        ports:
            - '80:80'
        networks:
            - deployer_network
        depends_on:
            - deploy_api
        restart: always

    deploy_api:
        container_name: deployer_api
        build:
            context: ./backend
        ports:
            - '5001:5001'
        networks:
            - deployer_network

    deploy_queue:
        container_name: deploy_queue
        build:
            context: ./queue/deploy
        networks:
            - deployer_network
        depends_on:
            - rabbitmq
        restart: always

networks:
    deployer_network:
