version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: insurance_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
    networks:
      - insurance_network

  insurance_db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - insurance_network

  insurance_api:
    container_name: insurance_api
    build:
      context: ./InsuranceBuilderPro
    ports:
      - "5001:5001"
    networks:
      - insurance_network

  insurance_client:
    container_name: insurance_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - insurance_network

  swms:
    container_name: swms
    build:
      context: ./pdf/swms
    networks:
      - insurance_network
    depends_on:
      - rabbitmq
    restart: always

  report:
    container_name: report
    build:
      context: ./pdf/report
    networks:
      - insurance_network
    depends_on:
      - rabbitmq
    restart: always

  scope:
    container_name: scope
    build:
      context: ./pdf/scope
    networks:
      - insurance_network
    depends_on:
      - rabbitmq
    restart: always
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - insurance_api
      - insurance_client
    networks:
      - insurance_network
    restart: always

networks:
  insurance_network: